/**
 * Bridge between requests and nextjs server
 *
 * @module shim
 */
const adapter = require("./http-adapter");

// This is generated by vercel output
const nextLauncher = require("./___next_launcher.cjs");

// TODO: include this patch as part of http-adapter
async function handler(req, res) {
  if (req.headers["content-type"] === "application/x-www-form-urlencoded") {
    req.body = Object.fromEntries(
      new URLSearchParams(req.body.toString()).entries()
    );
  }
  await nextLauncher(req, res);
}

module.exports = {
  handler: async (event) => {
    const response = await adapter(handler)(event);
    // add this as a temporal debug
    console.log(JSON.stringify(response));
    return response;
  },
};
